---
- name: Configure Steam runtime
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Ensure Steam exists on host
      community.general.pacman:
        name: steam
        state: present
        update_cache: true
      become: true

    - name: Verify Steam runtime
      ansible.builtin.command: steam --version
      changed_when: false
