---
- name: Install workstation packages
  community.general.pacman:
    name:
      - git
      - curl
      - wget
      - jq
      - rsync
      - zip
      - unzip
      - 7zip
      - openssh
      - fzf
      - ripgrep
      - fd
      - bat
      - eza
      - zoxide
      - btop
      - tmux
      - ansible
      - neovim
      - python
      - python-pip
      - python-virtualenv
      - nodejs
      - npm
      - nvm
      - openjdk
      - jdk-openjdk
      - maven
      - gradle
      - yq
      - distrobox
      - podman
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-jack
      - wireplumber
      - bluez
      - bluez-utils
    state: present
    update_cache: true

- name: Enable Bluetooth
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
    state: started
