#!/usr/bin/env python3
"""
Generate RPCS3 per-game custom configs for installed PS3 games.

Walks the PS3 ROM root, parses PARAM.SFO for each game's title ID,
queries the RPCS3 compatibility API, and writes a custom config YAML
to ~/.config/rpcs3/custom_configs/config_<TITLE_ID>.yml only when the
game's compatibility status indicates it benefits from tuning.

Filename convention: RPCS3 loads per-game configs from
`custom_configs/config_<SERIAL>.yml` — the `config_` prefix is
mandatory. Files named `<SERIAL>_config.yml` are silently ignored.

Strategy:
  - Playable: skip (defaults work)
  - Ingame:   apply common rendering fixes (Write Color Buffers etc.)
  - Loadable: apply aggressive fixes (likely won't help much)
  - Nothing:  skip (no point)

The generated config only sets keys that DIFFER from RPCS3 defaults.
Existing user-edited configs are NOT overwritten unless --force is given.

Usage:
    python3 generate_rpcs3_configs.py /path/to/ps3-roms \\
        [--dest ~/.config/rpcs3/custom_configs] \\
        [--dry-run] [--force]
"""

import json
import os
import re
import struct
import sys
import time
import urllib.request
from typing import Iterable

DEFAULT_DEST = os.path.expanduser("~/.config/rpcs3/custom_configs")
RPCS3_API = "https://rpcs3.net/compatibility?api=v1&g={tid}"
DISC_TITLE_RE = re.compile(rb"(?:^|\x00)((?:BL|BC)[A-Z]{2}[0-9]{5})")
PSN_TITLE_RE = re.compile(rb"(?:^|\x00)(NP[A-Z]{2}[0-9]{5})")
DIRNAME_TITLE_RE = re.compile(r"(BL|BC|NP)[A-Z-]?[A-Z]{1,2}[-_]?([0-9]{5})")


# Common overrides that fix the majority of "Ingame" status games.
# Keys not listed inherit RPCS3 global defaults.
COMMON_INGAME_OVERRIDES = """\
# Auto-generated by Ansible. Edit and add to dg_rpcs3_force=false to keep changes.
# Compatibility status: {status}
# Game: {title}
Video:
  Write Color Buffers: true
  Read Color Buffers: true
  Strict Rendering Mode: false
  Resolution Scale: 100
Core:
  SPU Block Size: Mega
"""

# Aggressive set for games marked "Loadable" — usually broken but worth trying.
LOADABLE_OVERRIDES = """\
# Auto-generated by Ansible. Edit and add to dg_rpcs3_force=false to keep changes.
# Compatibility status: {status}
# Game: {title}
Video:
  Write Color Buffers: true
  Read Color Buffers: true
  Read Depth Buffer: true
  Strict Rendering Mode: true
  Resolution Scale: 100
Core:
  SPU Block Size: Mega
  Accurate GETLLAR: true
  Accurate RSX reservation access: true
"""

# Per-title hand-curated overrides for known-problematic games.
# These take precedence over the generic status-based templates above.
# Sources: RPCS3 wiki, common community fixes for VK_ERROR_DEVICE_LOST etc.
KNOWN_GAME_CONFIGS = {
    # Gran Turismo 6: Write Color Buffers crashes NVIDIA drivers (DEVICE_LOST)
    # and causes the "black reflections" regression (RPCS3 issue #17453, still
    # open April 2026). Keep WCB/RCB off — rear-view mirror will be black
    # without them, known upstream limitation.
    #
    # Other settings from RPCS3 wiki + community (Apr 2026):
    # - Force CPU Blit is MANDATORY — stops the in-race screen flicker
    # - SPU Block Size = Mega (standard for GT6, not Safe — tested)
    # - SPU XFloat Accuracy = Accurate: ~10% perf gain, required for correct
    #   physics in GT6 per upstream testing
    # - Preferred SPU Threads = 2: best on modern CPUs for GT6
    # - Accurate RSX reservation access + Accurate xfloat + Accurate DFMA:
    #   correct GT6 physics/collision math
    # - Driver Wake-Up Delay = 1: reduces NVIDIA stutter
    # - Disable ZCull Occlusion Queries: speeds up GT6 RSX path
    # - Resolution Scale = 300 (4K): RTX 5090 holds 60 fps in-race on v1.05;
    #   on weaker GPUs reduce to 200 (1440p) or 150 (1080p scaled)
    # - Install game updates up to v1.05 only — v1.06+ regresses visuals
    "BCES01893": """\
# Auto-generated by Ansible — Gran Turismo 6 specific (NVIDIA-safe, April 2026).
# DO NOT enable Write Color Buffers — causes VK_ERROR_DEVICE_LOST on NVIDIA
# and the "black reflections" regression (RPCS3 issue #17453).
# Known limitation: rear-view mirror will be black/incorrect without WCB.
# Tested against v1.05; v1.06+ introduces further visual regressions.
Core:
  PPU Decoder: Recompiler (LLVM)
  SPU Decoder: Recompiler (LLVM)
  SPU Block Size: Mega
  Preferred SPU Threads: 2
  Accurate RSX reservation access: true
  # LLE the firmware music library. RPCS3's HLE cellMusic is stubbed
  # ("cellMusic TODO" in log); on race-finish GT6 polls
  # cellMusicGetPlaybackStatus2 forever waiting for a state change the
  # stub never produces — game appears frozen with music playing and no
  # UI. Loading the real firmware library breaks the loop.
  Libraries Control:
    - libsysutil_music.sprx:lle
    - libsysutil_music_decode.sprx:lle
    - libsysutil_music_export.sprx:lle
Video:
  Renderer: Vulkan
  # WCB/RCB OFF is a deliberate tradeoff for GT6:
  # - WCB would fix the rear-view mirror rendering, BUT RPCS3 force-
  #   downscales render targets to native (720p) when WCB is on, which
  #   crushes the 4K Resolution Scale for tracks and cars (HUD stays
  #   sharp because it's drawn in a separate pass). Upstream-fixed on
  #   real-hw, but no RPCS3 knob avoids the downsample. Pick: sharp 4K
  #   scene + black mirror, OR 720p scene + working mirror.
  # - Also dodges the v1.06+ "black reflections" regression
  #   (issue #17453, still open Apr 2026) that returns even when WCB
  #   technically works.
  Write Color Buffers: false
  Read Color Buffers: false
  Read Depth Buffer: false
  Strict Rendering Mode: false
  Resolution Scale: 300
  Anisotropic Filter Override: 16
  Multithreaded RSX: true
  # Async-with-Interpreter: RPCS3 runs the shader interpreter while new
  # shader combos compile in the background. Prevents car-preview stalls
  # in GT6's garage/shop as each new car model trips new shader permutations.
  Shader Mode: Async with Shader Interpreter
  Driver Wake-Up Delay: 1
  Vblank Rate: 60
  Force CPU Blit: true
  Disable ZCull Occlusion Queries: true
Audio:
  Enable Time Stretching: true
""",
    "BCAS25018": None,  # alias of BCES01893
    "BCES01977": None,
    "BCJS37016": None,
    "BCUS98296": None,

    # Metal Gear Solid 4 — needs WCB but also Strict Mode for cutscenes
    "BLES00246": """\
# Auto-generated by Ansible — MGS4 specific.
Video:
  Write Color Buffers: true
  Read Color Buffers: true
  Strict Rendering Mode: true
  Multithreaded RSX: false
  Resolution Scale: 100
Core:
  SPU Block Size: Mega
  Accurate GETLLAR: true
""",

    # Gran Turismo 5 — similar to GT6 but slightly more tolerant.
    # Visual tuning for 2026 on NVIDIA: 300% scale is the single biggest
    # fix for aliasing on shiny paint/glass; Shader Precision Ultra
    # reduces the "dither in dark areas" seen on PS3 HDR-tonemapped
    # shadows. WCB/RCB stay off to avoid the NVIDIA DEVICE_LOST /
    # black-reflections issue that hits the whole GT family.
    "BCUS98114": """\
# Auto-generated by Ansible — GT5 specific (NVIDIA-safe, April 2026).
# DO NOT enable Write Color Buffers — same NVIDIA DEVICE_LOST risk
# as GT6. Rear-view mirror will be black; known upstream limitation.
Core:
  PPU Decoder: Recompiler (LLVM)
  SPU Decoder: Recompiler (LLVM)
  SPU Block Size: Mega
  Preferred SPU Threads: 2
  Accurate RSX reservation access: true
Video:
  Renderer: Vulkan
  Write Color Buffers: false
  Read Color Buffers: false
  Read Depth Buffer: false
  Strict Rendering Mode: false
  Resolution Scale: 300
  Anisotropic Filter Override: 16
  Shader Precision: Ultra
  Force High Precision Z buffer: true
  Multithreaded RSX: true
  Driver Wake-Up Delay: 1
  Vblank Rate: 60
  Force CPU Blit: true
  Disable ZCull Occlusion Queries: true
Audio:
  Enable Time Stretching: true
""",

    # Codemasters DIRT/WRC family: all suffer from black car liveries (and
    # in DIRT 3's case, dark scenes) unless Write Color Buffers is on.
    # RPCS3.net lists them as Playable, so the generic "Ingame" generator
    # skips them — hand-curate a minimal override here.
    # DIRT 3 (EU). Also fixes generally dark rendering under Vulkan.
    "BLES01548": """\
# Auto-generated by Ansible — DIRT 3 specific.
# Write Color Buffers ON: required to render car liveries and HUD correctly.
Video:
  Write Color Buffers: true
  Read Color Buffers: true
  Strict Rendering Mode: false
  Resolution Scale: 100
Core:
  SPU Block Size: Mega
""",
    # WRC 4 FIA World Rally Championship (US). Same class of black-livery
    # bug as DIRT 3, same fix (Write Color Buffers).
    #
    # Red car/tire shadow artifacts (reported across WRC 3/4/5): NOT
    # fixed here. Tried Read/Write Depth Buffer ON — it made WRC 3 far
    # WORSE (whole terrain became red/green chromatic noise), so it was
    # reverted. No upstream wiki/issue documents a fix; left as a known
    # cosmetic issue rather than risk a worse regression.
    "BLUS31509": """\
# Auto-generated by Ansible — WRC 4 specific.
# Write Color Buffers ON: required to render car liveries correctly.
Video:
  Write Color Buffers: true
  Read Color Buffers: true
  Strict Rendering Mode: false
  Resolution Scale: 100
Core:
  SPU Block Size: Mega
""",
    # WRC 3 (US disc). WCB for liveries (DIRT/WRC family). See WRC 4 note
    # re: the red shadow artifact (depth-buffer attempt reverted).
    "BLUS31168": """\
# Auto-generated by Ansible — WRC 3 specific.
# Write Color Buffers ON: required to render car liveries correctly.
Video:
  Write Color Buffers: true
  Read Color Buffers: true
  Strict Rendering Mode: false
  Resolution Scale: 100
Core:
  SPU Block Size: Mega
""",
    # WRC 5 (US disc). Same family — WCB for liveries. See WRC 4 note.
    "BLUS31549": """\
# Auto-generated by Ansible — WRC 5 specific.
# Write Color Buffers ON: required to render car liveries correctly.
Video:
  Write Color Buffers: true
  Read Color Buffers: true
  Strict Rendering Mode: false
  Resolution Scale: 100
Core:
  SPU Block Size: Mega
""",
}


def get_game_specific_config(tid: str) -> str | None:
    """Return curated config for known-problematic games, else None."""
    cfg = KNOWN_GAME_CONFIGS.get(tid)
    # `None` value = alias of another title ID; resolve by checking which
    # other title in the dict points to a real config and shares prefix.
    if cfg is None and tid in KNOWN_GAME_CONFIGS:
        # Find sibling with same game (same wiki-id concept, manual mapping)
        # Simple heuristic: scan dict for non-None body and apply if title
        # is one of the documented aliases.
        for other_tid, body in KNOWN_GAME_CONFIGS.items():
            if body is None:
                continue
            # GT6 aliases all map to BCES01893
            if tid in ("BCAS25018", "BCES01977", "BCJS37016", "BCUS98296") and other_tid == "BCES01893":
                return body
    return cfg


def extract_title_id(sfo_path: str, dir_name: str) -> str | None:
    """Extract the disc-format title ID (BLxx12345 / BCxx12345).

    PARAM.SFO sometimes only contains the PSN/trophy ID (NPxx12345) which the
    RPCS3 compat API doesn't index, so we prefer disc IDs and fall back to
    parsing the directory name, which often includes the original disc ID.
    """
    try:
        with open(sfo_path, "rb") as f:
            data = f.read(4096)
    except OSError:
        return None

    # 1. Disc title ID inside PARAM.SFO — best signal
    match = DISC_TITLE_RE.search(data)
    if match:
        return match.group(1).decode("ascii")

    # 2. Disc title ID parsed from the directory name (handles BLUS-30016 etc.)
    for m in DIRNAME_TITLE_RE.finditer(dir_name):
        prefix = m.group(1)
        if prefix in ("BL", "BC"):
            return f"{prefix}US{m.group(2)}" if prefix == "BL" else f"{prefix}ES{m.group(2)}"
    # More forgiving second pass on dir name to catch variants like BLUS30016
    raw = re.search(r"(BL|BC)([A-Z]{2})[-_]?([0-9]{5})", dir_name)
    if raw:
        return f"{raw.group(1)}{raw.group(2)}{raw.group(3)}"

    # 3. Fall back to PSN/trophy ID (rarely matches in compat DB)
    match = PSN_TITLE_RE.search(data)
    return match.group(1).decode("ascii") if match else None


def find_games(ps3_root: str) -> dict:
    """Return dict of {title_id: (game_dir, game_name)} for installed games."""
    games = {}
    if not os.path.isdir(ps3_root):
        return games

    for entry in sorted(os.listdir(ps3_root)):
        game_dir = os.path.join(ps3_root, entry)
        sfo = os.path.join(game_dir, "PS3_GAME", "PARAM.SFO")
        if not os.path.isfile(sfo):
            continue
        tid = extract_title_id(sfo, entry)
        if not tid:
            continue
        # Strip trailing .ps3 directory naming convention
        name = entry[:-4] if entry.endswith(".ps3") else entry
        # Don't overwrite — first occurrence wins
        games.setdefault(tid, (game_dir, name))

    return games


def fetch_status(tid: str, retries: int = 2) -> str:
    """Query RPCS3 API for compatibility status. Returns one of:
    Playable, Ingame, Loadable, Nothing, Unknown."""
    url = RPCS3_API.format(tid=tid)
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(
                url, headers={"User-Agent": "ansible-distrobox-gaming/1.0"}
            )
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = json.loads(resp.read().decode("utf-8"))
        except Exception:
            if attempt < retries:
                time.sleep(1)
                continue
            return "Unknown"

        if data.get("return_code") != 0:
            return "Unknown"

        results = data.get("results") or {}
        # API returns multiple regional title IDs; prefer exact match
        if tid in results:
            return results[tid].get("status", "Unknown")
        # Fall back to first result if our exact ID isn't in the response
        if results:
            first = next(iter(results.values()))
            return first.get("status", "Unknown")
        return "Unknown"
    return "Unknown"


def render_config(tid: str, status: str, title: str) -> str | None:
    # Hand-curated overrides take precedence — these are documented fixes
    # for games that misbehave with the generic templates.
    curated = get_game_specific_config(tid)
    if curated is not None:
        return curated
    if status == "Ingame":
        return COMMON_INGAME_OVERRIDES.format(status=status, title=title)
    if status == "Loadable":
        return LOADABLE_OVERRIDES.format(status=status, title=title)
    # Playable / Nothing / Unknown -> no config written
    return None


def main(argv: Iterable[str]) -> int:
    args = list(argv)
    if not args:
        print(__doc__)
        return 1

    ps3_root = args[0]
    dest = DEFAULT_DEST
    dry_run = False
    force = False

    i = 1
    while i < len(args):
        a = args[i]
        if a == "--dest" and i + 1 < len(args):
            dest = args[i + 1]
            i += 2
        elif a == "--dry-run":
            dry_run = True
            i += 1
        elif a == "--force":
            force = True
            i += 1
        else:
            print(f"Unknown arg: {a}", file=sys.stderr)
            return 1

    games = find_games(ps3_root)
    if not games:
        print(f"No PS3 games found in {ps3_root}", file=sys.stderr)
        return 1

    if not dry_run:
        os.makedirs(dest, exist_ok=True)

    print(f"Found {len(games)} PS3 games. Querying RPCS3 compatibility API...")
    print(f"Destination: {dest}")
    if dry_run:
        print("DRY RUN — no files will be written")
    print()

    counts = {"written": 0, "skipped_existing": 0, "skipped_status": 0, "errors": 0}
    by_status: dict[str, int] = {}

    for tid, (_, name) in sorted(games.items()):
        status = fetch_status(tid)
        by_status[status] = by_status.get(status, 0) + 1

        body = render_config(tid, status, name)
        if body is None:
            print(f"  {tid}  {status:<10}  {name[:60]}  (no config needed)")
            counts["skipped_status"] += 1
            continue

        # RPCS3 expects custom_configs/config_<SERIAL>.yml — the `config_`
        # prefix is required; files named the other way round are ignored.
        config_path = os.path.join(dest, f"config_{tid}.yml")
        if os.path.exists(config_path) and not force:
            print(f"  {tid}  {status:<10}  {name[:60]}  (existing — keep)")
            counts["skipped_existing"] += 1
            continue

        if dry_run:
            print(f"  {tid}  {status:<10}  {name[:60]}  (would write)")
            counts["written"] += 1
            continue

        try:
            with open(config_path, "w") as f:
                f.write(body)
            print(f"  {tid}  {status:<10}  {name[:60]}  (written)")
            counts["written"] += 1
        except OSError as e:
            print(f"  {tid}  ERROR: {e}", file=sys.stderr)
            counts["errors"] += 1

        # Be polite to the API
        time.sleep(0.2)

    print()
    print("Status breakdown:")
    for status, n in sorted(by_status.items(), key=lambda x: -x[1]):
        print(f"  {status:<10} {n}")
    print()
    print(
        f"Complete: {counts['written']} written, "
        f"{counts['skipped_status']} skipped (status fine), "
        f"{counts['skipped_existing']} skipped (already exist), "
        f"{counts['errors']} errors"
    )
    return 0 if counts["errors"] == 0 else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
