---
- name: Create Dolphin config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ dg_dolphin_config_dir }}"
    - "{{ dg_dolphin_config_dir }}/Profiles/GCPad"
    - "{{ dg_dolphin_config_dir }}/Profiles/Wiimote"

- name: Copy Dolphin controller configs
  ansible.builtin.copy:
    src: "dolphin/{{ item }}"
    dest: "{{ dg_dolphin_config_dir }}/{{ item }}"
    backup: true
    mode: "0644"
  loop: "{{ dg_dolphin_configs }}"
